# Numpy Array Oluşturmak!

In [38]:
import numpy as np

In [39]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [40]:
a = np.array([1,2,3,4,5])

In [41]:
type(a)

numpy.ndarray

In [42]:
# Numpy'da sabit tip baskısı vardır. En yüksek veri tipine, eğer çevrilebilirse tabii, çevrilir.
# Aşağıda int'ler float tipine dönüştüler.
np.array([3.14, 2, 3, 4, 5, 6])

array([3.14, 2.  , 3.  , 4.  , 5.  , 6.  ])

In [43]:
# dtype parametresine argüman yollayarak istediğimiz tipte array oluşturabiliriz.
np.array([3.14, 4, 5, 6], dtype = "float32")

array([3.14, 4.  , 5.  , 6.  ], dtype=float32)

In [44]:
# Sıfırlardan oluşan array oluşturmak.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [54]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
# 3 satır 5 sütunluk birlerden oluşan array oluştur. Yani birim matris.
np.ones((3, 5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [47]:
# Ben bir veya sıfır değil kafama göre bir sayı ile array oluşturayım dersen..
np.full((3, 5), 100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [48]:
# range mantığı burdada var yine..
np.arange(0, 31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [49]:
# iki sayı arasında belirli sayıda değer oluştur dersek..
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [50]:
# dağılımını ben ayarlayayım, yani aritmetik ortalama ve medyan gireyim o değerler arasında oluştur dersek..
np.random.normal(10, 4, (3, 4))

array([[11.84985269,  5.72017752,  8.19120545, 15.63702993],
       [ 7.39867332, 11.3230713 , 11.29184774, 16.0960099 ],
       [11.53538879,  9.29380265, 15.77779213,  9.3185921 ]])

In [51]:
# Not: Tek boyutlu array vektördür.
# Not: İki boyutlu array matrisdir.

In [52]:
np.random.randint(0, 10, (3, 3))

array([[6, 6, 9],
       [7, 5, 3],
       [7, 9, 2]])